% function [Jac,Fun] = mybrussode_Jac(t,y,N)
% 
% Jacobian wrapper file generated by ADiGator
% ©2010-2014 Matthew J. Weinstein and Anil V. Rao
% ADiGator may be obtained at https://sourceforge.net/projects/adigator/ 
% Contact: mweinstein@ufl.edu
% Bugs/suggestions may be reported to the sourceforge forums
%                    DISCLAIMER
% ADiGator is a general-purpose software distributed under the GNU General
% Public License version 3.0. While the software is distributed with the
% hope that it will be useful, both the software and generated code are
% provided 'AS IS' with NO WARRANTIES OF ANY KIND and no merchantability
% or fitness for any purpose or application.

function [Jac,Fun] = mybrussode_Jac(t,y,N)
gator_y.f = y;
gator_y.dy = ones(16,1);
dydt = mybrussode_ADiGatorJac(t,gator_y,N);
Jac = sparse(dydt.dy_location(:,1),dydt.dy_location(:,2),dydt.dy,16,16);
Fun = dydt.f;
end